####---- test
#GET http://localhost:5000/api/Home/TestResponse?job=success
#GET https://localhost:7134/api/Home/TestResponse?job=success
#GET https://localhost:7134/api/Home/TestResponse?job=false

####---- test
GET https://localhost:7134/api/Home/twosecondtimeout/1000

####---- test
GET https://localhost:7134/api/Home/twosecondtimeout/3000

