GET https://localhost:7055/api/v1/WeatherForecast HTTP/1.1

###

POST https://localhost:7055/api/v1/Account/Login HTTP/1.1
Content-Type: application/json

{
    "login_name": "sato_ngword",
    "password": "password_bakaword"
}

###

Get https://localhost:7055/api/v1/Hoge/NoRoleHTTP/1.1

###

Get https://localhost:7055/api/v1/Hoge/AdminRole HTTP/1.1

###

Get https://localhost:7055/api/v1/Hoge/AnotherRole HTTP/1.1

###

Get https://localhost:7055/api/v1/Hoge/CheckParams
    ?name=sato
    &city=tokyo

###

Get https://localhost:7055/api/v1/Hoge/CheckAdminPolicy


###

Get https://localhost:7055/api/v1/Hoge/Person







